# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 07:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0030_auto_20171226_1055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('checked_out', models.BooleanField(default=False, verbose_name='\u041a\u043e\u0440\u0437\u0438\u043d\u0430 \u043e\u0444\u043e\u0440\u043c\u043b\u0435\u043d\u0430')),
                ('checkout_date', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0444\u043e\u0440\u043c\u043b\u0435\u043d\u0438\u044f')),
                ('country', models.CharField(blank=True, max_length=225, null=True, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430')),
                ('city', models.CharField(blank=True, max_length=225, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('address', models.TextField(blank=True, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('fio', models.CharField(blank=True, max_length=511, null=True, verbose_name='\u0418\u043c\u044f, \u0424\u0430\u043c\u0438\u043b\u0438\u044f, \u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u043d\u043e\u0432\u044b\u0439'), (1, '\u043f\u0440\u0438\u043d\u044f\u0442'), (2, '\u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d'), (3, '\u0438\u0441\u043f\u043e\u043b\u043d\u0435\u043d'), (4, '\u043e\u0442\u043c\u0435\u043d\u0435\u043d')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('summary', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u0440\u043e\u0444\u0438\u043b\u044c')),
            ],
            options={
                'ordering': ('-creation_date',),
                'verbose_name': '\u0437\u0430\u043a\u0430\u0437',
                'verbose_name_plural': '\u0437\u0430\u043a\u0430\u0437\u044b',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('extra_products', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('option_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('wrapping_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ProductOption', verbose_name='\u0412\u0430\u0440\u0438\u0430\u043d\u0442')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440')),
            ],
            options={
                'ordering': ('cart', '-id'),
                'verbose_name': '\u0442\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u0442\u043e\u0432\u0430\u0440\u044b',
            },
        ),
    ]
