# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='fio',
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(blank=True, max_length=511, null=True, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u0438\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Country', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430'),
        ),
    ]
