# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20171229_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='summary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0421\u0443\u043c\u043c\u0430, \u0440\u0443\u0431.'),
        ),
    ]
