# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20180109_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
