# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 17:26
from __future__ import unicode_literals

from django.db import migrations


def load_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', '20180126_cart_methods.json')


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20180126_1941'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=migrations.RunPython.noop),
    ]
