# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20180126_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_paypal',
            field=models.BooleanField(default=False, verbose_name='\u041e\u043f\u043b\u0430\u0442\u0430 \u0447\u0435\u0440\u0435\u0437 PayPal'),
        ),
    ]
