# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_paymentmethod_is_paypal'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d?'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d?'),
        ),
    ]
