# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_h1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0010_auto_20180212_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('checked_out', models.BooleanField(default=False, verbose_name='\u041a\u043e\u0440\u0437\u0438\u043d\u0430 \u043e\u0444\u043e\u0440\u043c\u043b\u0435\u043d\u0430')),
                ('checkout_date', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0444\u043e\u0440\u043c\u043b\u0435\u043d\u0438\u044f')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f \u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044f')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Email \u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044f')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='\u0418\u043c\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044f')),
                ('sender_phone', models.CharField(max_length=127, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044f')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='Email \u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044f')),
                ('message', models.TextField(blank=True, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044e')),
                ('send_immediately', models.BooleanField(default=True, verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u044f\u0442\u044c \u0441\u0440\u0430\u0437\u0443?')),
                ('send_date', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '\u043d\u043e\u0432\u044b\u0439'), (1, '\u043f\u0440\u0438\u043d\u044f\u0442'), (2, '\u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d'), (3, '\u0438\u0441\u043f\u043e\u043b\u043d\u0435\u043d'), (4, '\u043e\u0442\u043c\u0435\u043d\u0435\u043d')], default=0, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('summary', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0421\u0443\u043c\u043c\u0430, \u0440\u0443\u0431.')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catalog.Certificate', verbose_name='\u0421\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442')),
                ('delivery_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.DeliveryMethod', verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.PaymentMethod', verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u043e\u043f\u043b\u0430\u0442\u044b')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_orders', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u0440\u043e\u0444\u0438\u043b\u044c')),
            ],
            options={
                'ordering': ('-creation_date',),
                'verbose_name': '\u0437\u0430\u043a\u0430\u0437 \u0441\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u0430',
                'verbose_name_plural': '\u0437\u0430\u043a\u0430\u0437\u044b \u0441\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0432',
            },
        ),
    ]
