# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_h1'),
        ('cart', '0011_certificateorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateCartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f \u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044f')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Email \u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044f')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='\u0418\u043c\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044f')),
                ('sender_phone', models.CharField(max_length=127, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044f')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='Email \u043e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u0435\u043b\u044f')),
                ('message', models.TextField(blank=True, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044e')),
                ('send_immediately', models.BooleanField(default=True, verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u044f\u0442\u044c \u0441\u0440\u0430\u0437\u0443?')),
                ('send_date', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.Certificate', verbose_name='\u0421\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442')),
            ],
            options={
                'ordering': ('cart', '-id'),
                'verbose_name': '\u0441\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442',
                'verbose_name_plural': '\u0441\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u044b',
            },
        ),
        migrations.RemoveField(
            model_name='certificateorder',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='certificateorder',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='certificateorder',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='certificateorder',
            name='profile',
        ),
        migrations.DeleteModel(
            name='CertificateOrder',
        ),
    ]
