# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20180212_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='hash',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
