# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_cartitem_hash'),
    ]

    operations = [
        # pass
        # migrations.RunPython(set_hashes, reverse_code=migrations.RunPython.noop),
    ]
