# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_set_hashes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='hash',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
