# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 16:07
from __future__ import unicode_literals

import copy

from django.db import migrations

from ..utils import make_hash


def _set_hash(obj):
    hash = 0
    if obj.extra_products:
        x = copy.deepcopy(obj.attrs)
        x.update(obj.extra_products)
        hash = make_hash(x)
    else:
        hash = make_hash(obj.attrs)
    obj.hash = hash
    obj.save()
    return hash


def set_hashes(apps, schema_editor):
    CartItem = apps.get_model('cart', 'CartItem')
    for c in CartItem.objects.all().order_by('-id'):
        _set_hash(c)
        print c.id, c.hash


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20180225_1906'),
    ]

    operations = [
        migrations.RunPython(set_hashes, reverse_code=migrations.RunPython.noop),
    ]
