# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 16:07
from __future__ import unicode_literals

import copy

from django.db import migrations

from ..utils import make_hash_from_cartitem


def set_hashes(apps, schema_editor):
    CartItem = apps.get_model('cart', 'CartItem')
    for c in CartItem.objects.all().order_by('-id'):
        c.hash = make_hash_from_cartitem(c.attrs, c.extra_products)
        c.save()
        print c.id, c.hash


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_auto_20180225_1906'),
    ]

    operations = [
        migrations.RunPython(set_hashes, reverse_code=migrations.RunPython.noop),
    ]
