# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_set_hashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='currency',
            field=models.CharField(choices=[('rub', 'RUB'), ('eur', 'EUR'), ('usd', 'USD')], default='rub', max_length=3, verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430'),
        ),
    ]
