# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_cart_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='with_wrapping',
            field=models.BooleanField(default=False),
        ),
    ]
