# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 11:19
from __future__ import unicode_literals

from django.db import migrations


def set_with_wrapping(apps, schema_editor):
    CartItem = apps.get_model('cart', 'CartItem')
    CartItem.objects.filter(wrapping_price__gt=0).update(with_wrapping=True)


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_cart_with_wrapping'),
    ]

    operations = [
        migrations.RunPython(set_with_wrapping, reverse_code=migrations.RunPython.noop),
    ]
