# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_cart_with_wrapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='summary',
            new_name='summary_rub',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='extra_price',
            new_name='extra_price_rub',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='option_price',
            new_name='option_price_rub',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='price',
            new_name='price_rub',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='wrapping_price',
            new_name='wrapping_price_rub',
        ),
        migrations.RenameField(
            model_name='certificatecartitem',
            old_name='price',
            new_name='price_rub',
        ),
    ]
