# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_rub_eur_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='summary_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0421\u0443\u043c\u043c\u0430, eur.'),
        ),
        migrations.AddField(
            model_name='cart',
            name='summary_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0421\u0443\u043c\u043c\u0430, usd.'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='extra_price_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='extra_price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='option_price_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='option_price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='wrapping_price_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='wrapping_price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='certificatecartitem',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='certificatecartitem',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
