# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 14:05
from __future__ import unicode_literals

from django.db import migrations


def save_currency_prices(apps, schema_editor):
    Cart = apps.get_model('cart', 'Cart')
    CartItem = apps.get_model('cart', 'CartItem')
    CertificateCartItem = apps.get_model('cart', 'CertificateCartItem')

    print; print; print 'CartItem...'
    for obj in CartItem.objects.select_related('product', 'option').prefetch_related('product__extra_options').order_by('-id'):
        obj.save()
        print obj.id, obj.price_rub, obj.price_eur, obj.price_usd

    print; print; print 'CertificateCartItem...'
    for obj in CertificateCartItem.objects.select_related('certificate').order_by('-id'):
        obj.save()
        print obj.id, obj.price_rub, obj.price_eur, obj.price_usd

    print; print; print 'Cart...'
    for obj in Cart.objects.prefetch_related('cartitem_set', 'certificatecartitem_set').order_by('-id'):
        obj.save()
        print obj.id, obj.summary_rub, obj.summary_eur, obj.summary_usd


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_rub_eur_usd'),
    ]

    operations = [
        migrations.RunPython(save_currency_prices, reverse_code=migrations.RunPython.noop),
    ]
