# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-09 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_rub_eur_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='delivery_methods',
            field=models.ManyToManyField(blank=True, related_name='payment_methods', to='cart.DeliveryMethod', verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431\u044b \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'),
        ),
    ]
