# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-09 12:53
from __future__ import unicode_literals

from django.db import migrations


def set_delivery_methods(apps, schema_editor):
    DeliveryMethod = apps.get_model('cart', 'DeliveryMethod')
    PaymentMethod = apps.get_model('cart', 'PaymentMethod')

    delivery_ids = DeliveryMethod.objects.all().values_list('id', flat=True)

    for obj in PaymentMethod.objects.all():
        print
        obj.delivery_methods = delivery_ids
        obj.save()
        print obj.id, obj.delivery_methods.values_list('id', flat=True)


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_paymentmethod_delivery_methods'),
    ]

    operations = [
        migrations.RunPython(set_delivery_methods, reverse_code=migrations.RunPython.noop),
    ]
