# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_paymentmethod_delivery_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='postal_code',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u0438\u043d\u0434\u0435\u043a\u0441'),
        ),
    ]
