# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-05 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_yandex_metrika'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-checkout_date',), 'verbose_name': '\u0437\u0430\u043a\u0430\u0437', 'verbose_name_plural': '\u0437\u0430\u043a\u0430\u0437\u044b'},
        ),
    ]
