# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-12-15 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0032_cart_yookassa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
    ]
