# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-12-15 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0033_cart_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='yoo_popup_showed',
            field=models.BooleanField(default=False),
        ),
    ]
