# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-12-15 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0034_cart_yoo_popup_showed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='\u0434\u043b\u044f \u043e\u043f\u043b\u0430\u0442\u044b \u043e\u043d\u043b\u0430\u0439\u043d', null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='yoo_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='YooKassa: ID \u043f\u043b\u0430\u0442\u0435\u0436\u0430'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='yoo_paid',
            field=models.NullBooleanField(default=None, verbose_name='YooKassa: \u041e\u043f\u043b\u0430\u0447\u0435\u043d?'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='yoo_redirect_url',
            field=models.URLField(blank=True, null=True, verbose_name='YooKassa: URL \u0434\u043b\u044f \u043f\u0435\u0440\u0435\u043d\u0430\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='yoo_status',
            field=models.CharField(blank=True, choices=[('pending', '\u043d\u0435 \u043e\u043f\u043b\u0430\u0447\u0435\u043d'), ('succeeded', '\u043e\u043f\u043b\u0430\u0447\u0435\u043d'), ('canceled', '\u043e\u0442\u043c\u0435\u043d\u0435\u043d'), ('error', '\u043e\u0448\u0438\u0431\u043a\u0430')], default='', max_length=15, null=True, verbose_name='YooKassa: \u0421\u0442\u0430\u0442\u0443\u0441 \u043f\u043b\u0430\u0442\u0435\u0436\u0430'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='yoo_test',
            field=models.NullBooleanField(default=None, verbose_name='YooKassa: \u0422\u0435\u0441\u0442\u043e\u0432\u044b\u0439 \u043f\u043b\u0430\u0442\u0435\u0436?'),
        ),
    ]
