# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-03-02 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0040_methods_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='life_pay_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Life Pay: ID'),
        ),
    ]
