# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-09-27 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0041_auto_20220302_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='robokassa_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='RoboKassa: ID \u043f\u043b\u0430\u0442\u0435\u0436\u0430'),
        ),
        migrations.AddField(
            model_name='cart',
            name='robokassa_paid',
            field=models.NullBooleanField(default=None, verbose_name='RoboKassa: \u041e\u043f\u043b\u0430\u0447\u0435\u043d?'),
        ),
        migrations.AddField(
            model_name='cart',
            name='robokassa_status',
            field=models.CharField(blank=True, choices=[('pending', '\u043d\u0435 \u043e\u043f\u043b\u0430\u0447\u0435\u043d'), ('succeeded', '\u043e\u043f\u043b\u0430\u0447\u0435\u043d'), ('canceled', '\u043e\u0442\u043c\u0435\u043d\u0435\u043d'), ('error', '\u043e\u0448\u0438\u0431\u043a\u0430')], default='', max_length=15, null=True, verbose_name='RoboKassa: \u0421\u0442\u0430\u0442\u0443\u0441 \u043f\u043b\u0430\u0442\u0435\u0436\u0430'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ru', 'RU'), ('en', 'EN'), ('de', 'DE'), ('es', 'ES'), ('fr', 'FR'), ('it', 'IT')], default=['ru', 'en', 'de', 'es', 'fr', 'it'], max_length=255, null=True, verbose_name='\u042f\u0437\u044b\u043a\u043e\u0432\u044b\u0435 \u0440\u0430\u0437\u0434\u0435\u043b\u044b'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ru', 'RU'), ('en', 'EN'), ('de', 'DE'), ('es', 'ES'), ('fr', 'FR'), ('it', 'IT')], default=['ru', 'en', 'de', 'es', 'fr', 'it'], max_length=255, null=True, verbose_name='\u042f\u0437\u044b\u043a\u043e\u0432\u044b\u0435 \u0440\u0430\u0437\u0434\u0435\u043b\u044b'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('yookassa', 'YooKassa'), ('robokassa', 'Robokassa'), ('paypal', 'PayPal'), ('offline', '\u043d\u0430\u043b\u0438\u0447\u043d\u044b\u0435')], default='offline', max_length=15, verbose_name='\u0422\u0438\u043f \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
    ]
