# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-09-27 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0042_auto_20220927_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='robokassa_url',
            field=models.URLField(blank=True, null=True, verbose_name='RoboKassa: URL'),
        ),
    ]
