# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-09-27 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0043_cart_robokassa_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='robokassa_id',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='RoboKassa: ID \u043f\u043b\u0430\u0442\u0435\u0436\u0430'),
        ),
    ]
