# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-09-27 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0044_auto_20220927_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='robokassa_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='RoboKassa: URL'),
        ),
    ]
