# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-09-29 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0045_auto_20220927_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='robokassa_signature',
            field=models.CharField(blank=True, max_length=310, null=True, verbose_name='RoboKassa: \u0421\u0438\u0433\u043d\u0430\u0442\u0443\u0440\u0430'),
        ),
    ]
