# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-09-28 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0046_cart_robokassa_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='robokassa_token',
            field=models.CharField(blank=True, default='', max_length=310, null=True, verbose_name='RoboKassa: \u0422\u043e\u043a\u0435\u043d'),
        ),
    ]
