# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-02-02 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0046_cart_robokassa_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
    ]
