# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-07-20 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0047_cartitem_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='robokassa_url',
            field=models.TextField(blank=True, null=True, verbose_name='RoboKassa: URL'),
        ),
    ]
