# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-09-28 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0047_auto_20220928_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='robokassa_token',
            field=models.CharField(blank=True, max_length=310, null=True, verbose_name='RoboKassa: \u0422\u043e\u043a\u0435\u043d'),
        ),
    ]
