# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-09-28 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0048_auto_20220928_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='robokassa_token',
        ),
    ]
