# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-07-24 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0048_auto_20240720_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='retailcrm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RetailCRM'),
        ),
    ]
