# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-07-24 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0049_cart_retailcrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='code_retailcrm',
            field=models.CharField(blank=True, max_length=511, null=True, verbose_name='\u0421\u0438\u043c\u0432\u043e\u043b\u044c\u043d\u044b\u0439 \u043a\u043e\u0434 \u0442\u0438\u043f\u043e\u0432 \u0434\u043e\u0441\u0442\u0430\u0432\u043e\u043a \u0438\u0437 retailcrm'),
        ),
    ]
