# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-08-09 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0051_paymentmethod_code_retailcrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
