# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-09-10 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0052_cart_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_one_click',
            field=models.BooleanField(default=False, help_text='\u041d\u0443\u0436\u043d\u043e \u0441\u0432\u044f\u0437\u0430\u0442\u044c\u0441\u044f \u0441 \u043f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u0435\u043c, \u0447\u0442\u043e\u0431\u044b \u0443\u0442\u043e\u0447\u043d\u0438\u0442\u044c \u0440\u0430\u0437\u043c\u0435\u0440, \u0446\u0432\u0435\u0442 \u0438 \u0443\u0441\u043b\u043e\u0432\u0438\u044f \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438', verbose_name='\u041f\u043e\u043a\u0443\u043f\u043a\u0430 \u0432 1 \u043a\u043b\u0438\u043a'),
        ),
    ]
