# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eur',
            name='celery_task_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usd',
            name='celery_task_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
