# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-03-03 08:38
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20180518_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eur',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('71.18'), max_digits=6, verbose_name='\u041a\u0443\u0440\u0441 \u0435\u0432\u0440\u043e'),
        ),
        migrations.AlterField(
            model_name='usd',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('61.98'), max_digits=6, verbose_name='\u041a\u0443\u0440\u0441 \u0434\u043e\u043b\u043b\u0430\u0440\u0430'),
        ),
    ]
