# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-25 06:55
from __future__ import unicode_literals

from django.db import migrations


def load_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', '20171025_menu.json')


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20171025_0951'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=migrations.RunPython.noop),
    ]
