# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-25 07:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_load_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageslider',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='homepageslider',
            name='description_ru',
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='description_h1',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (h1)'),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='description_h1_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (h1)'),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='description_h1_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (h1)'),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='description_p',
            field=models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='description_p_en',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='description_p_ru',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='description_picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='homepage_slider/pictures/', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430)'),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
