# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-25 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20171025_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageslider',
            name='description_picture_alt',
            field=models.CharField(blank=True, max_length=127, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (alt \u0443 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438)'),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='description_picture_alt_en',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (alt \u0443 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438)'),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='description_picture_alt_ru',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (alt \u0443 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438)'),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='description_picture_en',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='homepage_slider/pictures/', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430)'),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='description_picture_ru',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='homepage_slider/pictures/', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430)'),
        ),
    ]
