# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-27 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20171025_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomepageSlider',
        ),
    ]
