# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 04:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20171124_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='meta_desc',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_desc_de',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_desc_en',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_desc_es',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_desc_fr',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_desc_it',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_desc_ru',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_keyw',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, verbose_name='Meta keywords (\u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e)'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_keyw_de',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta keywords (\u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e)'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_keyw_en',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta keywords (\u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e)'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_keyw_es',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta keywords (\u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e)'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_keyw_fr',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta keywords (\u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e)'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_keyw_it',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta keywords (\u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e)'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_keyw_ru',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta keywords (\u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e)'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_title',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_title_de',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_title_es',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_title_fr',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_title_it',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_title_ru',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 "\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a"', max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='video',
            name='seo_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='video',
            name='seo_text_de',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='video',
            name='seo_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='video',
            name='seo_text_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='video',
            name='seo_text_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='video',
            name='seo_text_it',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='video',
            name='seo_text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='video',
            name='show_at_list',
            field=models.BooleanField(default=True, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0432 \u0441\u043f\u0438\u0441\u043a\u0435 \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 "\u0432\u0438\u0434\u0435\u043e"'),
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='default', max_length=127, verbose_name='\u0412 URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='slug_de',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
        migrations.AddField(
            model_name='video',
            name='slug_en',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
        migrations.AddField(
            model_name='video',
            name='slug_es',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
        migrations.AddField(
            model_name='video',
            name='slug_fr',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
        migrations.AddField(
            model_name='video',
            name='slug_it',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
        migrations.AddField(
            model_name='video',
            name='slug_ru',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
    ]
