# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 16:15
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='seo_text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_text_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_text_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_text_es',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_text_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_text_it',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_text_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='video',
            name='seo_text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='video',
            name='seo_text_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='video',
            name='seo_text_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='video',
            name='seo_text_es',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='video',
            name='seo_text_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='video',
            name='seo_text_it',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='video',
            name='seo_text_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
    ]
