# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('content', '0016_ckeditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='blog.Post', verbose_name='\u041f\u043e\u0441\u0442 \u0432 \u0431\u043b\u043e\u0433\u0435'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=b'', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
    ]
