# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20180227_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug_de',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u0432 url'),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u0432 url'),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_es',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u0432 url'),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u0432 url'),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_it',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u0432 url'),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_ru',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u0432 url'),
        ),
    ]
