# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 14:23
from __future__ import unicode_literals

from django.db import migrations


def set_slug(apps, schema_editor):
    """
    FROM: https://raphaelbeck.wordpress.com/2011/04/16/how-to-translate-slug-with-django-modeltranslation/
    """
    from uuslug import slugify
    from django.conf import settings

    Page = apps.get_model('content', 'Page')

    for obj in Page.objects.all():
        for lang_code, lang_verbose in settings.LANGUAGES:
            setattr(obj, 'slug_%s' % lang_code, slugify(getattr(obj, 'title_%s' % lang_code) or obj.title_ru)[:127])
        setattr(obj, 'slug', getattr(obj, 'slug_ru'))
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_auto_20180227_1722'),
    ]

    operations = [
        migrations.RunPython(set_slug, reverse_code=migrations.RunPython.noop),
    ]
