# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 09:29
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='h1_nsk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 (\u041d\u043e\u0432\u043e\u0441\u0438\u0431\u0438\u0440\u0441\u043a)'),
        ),
        migrations.AddField(
            model_name='page',
            name='h1_sam',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 (\u0421\u0430\u043c\u0430\u0440\u0430)'),
        ),
        migrations.AddField(
            model_name='page',
            name='h1_spb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 (\u0421\u0430\u043d\u043a\u0442-\u041f\u0435\u0442\u0435\u0440\u0431\u0443\u0440\u0433)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_desc_nsk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta description (\u041d\u043e\u0432\u043e\u0441\u0438\u0431\u0438\u0440\u0441\u043a)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_desc_sam',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta description (\u0421\u0430\u043c\u0430\u0440\u0430)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_desc_spb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta description (\u0421\u0430\u043d\u043a\u0442-\u041f\u0435\u0442\u0435\u0440\u0431\u0443\u0440\u0433)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_keyw_nsk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta keywords (\u041d\u043e\u0432\u043e\u0441\u0438\u0431\u0438\u0440\u0441\u043a)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_keyw_sam',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta keywords (\u0421\u0430\u043c\u0430\u0440\u0430)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_keyw_spb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta keywords (\u0421\u0430\u043d\u043a\u0442-\u041f\u0435\u0442\u0435\u0440\u0431\u0443\u0440\u0433)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_nsk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title (\u041d\u043e\u0432\u043e\u0441\u0438\u0431\u0438\u0440\u0441\u043a)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_sam',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title (\u0421\u0430\u043c\u0430\u0440\u0430)'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title_spb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title (\u0421\u0430\u043d\u043a\u0442-\u041f\u0435\u0442\u0435\u0440\u0431\u0443\u0440\u0433)'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_text_nsk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442 (\u041d\u043e\u0432\u043e\u0441\u0438\u0431\u0438\u0440\u0441\u043a)'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_text_sam',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442 (\u0421\u0430\u043c\u0430\u0440\u0430)'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_text_spb',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442 (\u0421\u0430\u043d\u043a\u0442-\u041f\u0435\u0442\u0435\u0440\u0431\u0443\u0440\u0433)'),
        ),
        migrations.AddField(
            model_name='video',
            name='h1_nsk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 (\u041d\u043e\u0432\u043e\u0441\u0438\u0431\u0438\u0440\u0441\u043a)'),
        ),
        migrations.AddField(
            model_name='video',
            name='h1_sam',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 (\u0421\u0430\u043c\u0430\u0440\u0430)'),
        ),
        migrations.AddField(
            model_name='video',
            name='h1_spb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='H1 (\u0421\u0430\u043d\u043a\u0442-\u041f\u0435\u0442\u0435\u0440\u0431\u0443\u0440\u0433)'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_desc_nsk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta description (\u041d\u043e\u0432\u043e\u0441\u0438\u0431\u0438\u0440\u0441\u043a)'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_desc_sam',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta description (\u0421\u0430\u043c\u0430\u0440\u0430)'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_desc_spb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta description (\u0421\u0430\u043d\u043a\u0442-\u041f\u0435\u0442\u0435\u0440\u0431\u0443\u0440\u0433)'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_keyw_nsk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta keywords (\u041d\u043e\u0432\u043e\u0441\u0438\u0431\u0438\u0440\u0441\u043a)'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_keyw_sam',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta keywords (\u0421\u0430\u043c\u0430\u0440\u0430)'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_keyw_spb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta keywords (\u0421\u0430\u043d\u043a\u0442-\u041f\u0435\u0442\u0435\u0440\u0431\u0443\u0440\u0433)'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_title_nsk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title (\u041d\u043e\u0432\u043e\u0441\u0438\u0431\u0438\u0440\u0441\u043a)'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_title_sam',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title (\u0421\u0430\u043c\u0430\u0440\u0430)'),
        ),
        migrations.AddField(
            model_name='video',
            name='meta_title_spb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta title (\u0421\u0430\u043d\u043a\u0442-\u041f\u0435\u0442\u0435\u0440\u0431\u0443\u0440\u0433)'),
        ),
        migrations.AddField(
            model_name='video',
            name='seo_text_nsk',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442 (\u041d\u043e\u0432\u043e\u0441\u0438\u0431\u0438\u0440\u0441\u043a)'),
        ),
        migrations.AddField(
            model_name='video',
            name='seo_text_sam',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442 (\u0421\u0430\u043c\u0430\u0440\u0430)'),
        ),
        migrations.AddField(
            model_name='video',
            name='seo_text_spb',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442 (\u0421\u0430\u043d\u043a\u0442-\u041f\u0435\u0442\u0435\u0440\u0431\u0443\u0440\u0433)'),
        ),
    ]
