# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-07-24 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_pageaccordeonsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/uploaded/', verbose_name='\u0412\u0438\u0434\u0435\u043e\u0444\u0430\u0439\u043b'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_source',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('file', '\u0424\u0430\u0439\u043b')], default='youtube', max_length=10, verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a \u0432\u0438\u0434\u0435\u043e'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 YouTube'),
        ),
    ]
