# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-08-22 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['order', 'id'], 'verbose_name': '\u0421\u043b\u0430\u0439\u0434', 'verbose_name_plural': '\u0421\u043b\u0430\u0439\u0434\u044b'},
        ),
        migrations.AddField(
            model_name='slide',
            name='order',
            field=models.IntegerField(default=10, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a'),
        ),
    ]
