# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 15:34
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'ordering': ['order', 'add_dt'], 'verbose_name': '\u0444\u043e\u0442\u043e', 'verbose_name_plural': '\u0433\u0430\u043b\u0435\u0440\u0435\u044f'},
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='', upload_to=b'', verbose_name='\u041e\u0431\u043b\u043e\u0436\u043a\u0430'),
            preserve_default=False,
        ),
    ]
