# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-09-27 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_another_three_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='lang',
            field=models.CharField(choices=[('ru', '\u0420\u0443\u0441\u0441\u043a\u0438\u0439'), ('en', 'English'), ('de', 'Deutsch'), ('es', 'Espa\xf1ol'), ('fr', 'Fran\xe7ais'), ('it', 'Italiano')], default='ru', max_length=4, verbose_name='\u042f\u0437\u044b\u043a'),
        ),
    ]
