# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-19 15:15
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosetting',
            name='seo_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='seo_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='seo_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='visualsetting',
            name='value',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='visualsetting',
            name='value_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='visualsetting',
            name='value_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
    ]
