# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 03:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20171019_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='seosetting',
            name='description_de',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='description_es',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='description_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='description_it',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='meta_desc_de',
            field=models.TextField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b (\u0432\u044b\u0448\u0435)', max_length=255, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='meta_desc_es',
            field=models.TextField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b (\u0432\u044b\u0448\u0435)', max_length=255, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='meta_desc_fr',
            field=models.TextField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b (\u0432\u044b\u0448\u0435)', max_length=255, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='meta_desc_it',
            field=models.TextField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b (\u0432\u044b\u0448\u0435)', max_length=255, null=True, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='meta_keyw_de',
            field=models.TextField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b (\u0432\u044b\u0448\u0435)', max_length=255, null=True, verbose_name='Meta keywords (\u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e)'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='meta_keyw_es',
            field=models.TextField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b (\u0432\u044b\u0448\u0435)', max_length=255, null=True, verbose_name='Meta keywords (\u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e)'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='meta_keyw_fr',
            field=models.TextField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b (\u0432\u044b\u0448\u0435)', max_length=255, null=True, verbose_name='Meta keywords (\u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e)'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='meta_keyw_it',
            field=models.TextField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b (\u0432\u044b\u0448\u0435)', max_length=255, null=True, verbose_name='Meta keywords (\u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e)'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='seo_text_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='seo_text_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='seo_text_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='seo_text_it',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='title_de',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b (\u0432\u044b\u0448\u0435)', max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='title_es',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b (\u0432\u044b\u0448\u0435)', max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='title_fr',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b (\u0432\u044b\u0448\u0435)', max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='seosetting',
            name='title_it',
            field=models.CharField(blank=True, help_text='\u041e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b (\u0432\u044b\u0448\u0435)', max_length=255, null=True, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='setting',
            name='value_de',
            field=models.TextField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='setting',
            name='value_es',
            field=models.TextField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='setting',
            name='value_fr',
            field=models.TextField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='setting',
            name='value_it',
            field=models.TextField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='visualsetting',
            name='value_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='visualsetting',
            name='value_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='visualsetting',
            name='value_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='visualsetting',
            name='value_it',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
    ]
