# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 16:10
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_new_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosetting',
            name='seo_text',
            field=tinymce.models.HTMLField(blank=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='seo_text_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='seo_text_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='seo_text_es',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='seo_text_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='seo_text_it',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='seosetting',
            name='seo_text_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='visualsetting',
            name='value',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='visualsetting',
            name='value_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='visualsetting',
            name='value_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='visualsetting',
            name='value_es',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='visualsetting',
            name='value_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='visualsetting',
            name='value_it',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='visualsetting',
            name='value_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
    ]
