# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 05:58
from __future__ import unicode_literals

from django.db import migrations


def load_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', '20171204_seosettings.json')


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20171203_1910'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=migrations.RunPython.noop),
    ]
