# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-30 10:18
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='catalog_special_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441 \u0430\u043a\u0446\u0438\u044f\u043c\u0438 \u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0435'),
        ),
    ]
