# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-16 18:29
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_settings_catalog_special_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='catalog_special_banner',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='\u0411\u0443\u0434\u0435\u0442 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c\u0441\u044f \u0432 \u0440\u0430\u0437\u043c\u0435\u0440\u0435 851x315 px', null=True, upload_to='b/catalog/', verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440 \u0441 \u0430\u043a\u0446\u0438\u044f\u043c\u0438'),
        ),
        migrations.AddField(
            model_name='settings',
            name='catalog_special_banner_de',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='\u0411\u0443\u0434\u0435\u0442 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c\u0441\u044f \u0432 \u0440\u0430\u0437\u043c\u0435\u0440\u0435 851x315 px', null=True, upload_to='b/catalog/', verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440 \u0441 \u0430\u043a\u0446\u0438\u044f\u043c\u0438'),
        ),
        migrations.AddField(
            model_name='settings',
            name='catalog_special_banner_en',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='\u0411\u0443\u0434\u0435\u0442 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c\u0441\u044f \u0432 \u0440\u0430\u0437\u043c\u0435\u0440\u0435 851x315 px', null=True, upload_to='b/catalog/', verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440 \u0441 \u0430\u043a\u0446\u0438\u044f\u043c\u0438'),
        ),
        migrations.AddField(
            model_name='settings',
            name='catalog_special_banner_es',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='\u0411\u0443\u0434\u0435\u0442 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c\u0441\u044f \u0432 \u0440\u0430\u0437\u043c\u0435\u0440\u0435 851x315 px', null=True, upload_to='b/catalog/', verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440 \u0441 \u0430\u043a\u0446\u0438\u044f\u043c\u0438'),
        ),
        migrations.AddField(
            model_name='settings',
            name='catalog_special_banner_fr',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='\u0411\u0443\u0434\u0435\u0442 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c\u0441\u044f \u0432 \u0440\u0430\u0437\u043c\u0435\u0440\u0435 851x315 px', null=True, upload_to='b/catalog/', verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440 \u0441 \u0430\u043a\u0446\u0438\u044f\u043c\u0438'),
        ),
        migrations.AddField(
            model_name='settings',
            name='catalog_special_banner_it',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='\u0411\u0443\u0434\u0435\u0442 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c\u0441\u044f \u0432 \u0440\u0430\u0437\u043c\u0435\u0440\u0435 851x315 px', null=True, upload_to='b/catalog/', verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440 \u0441 \u0430\u043a\u0446\u0438\u044f\u043c\u0438'),
        ),
        migrations.AddField(
            model_name='settings',
            name='catalog_special_banner_ru',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='\u0411\u0443\u0434\u0435\u0442 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c\u0441\u044f \u0432 \u0440\u0430\u0437\u043c\u0435\u0440\u0435 851x315 px', null=True, upload_to='b/catalog/', verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440 \u0441 \u0430\u043a\u0446\u0438\u044f\u043c\u0438'),
        ),
        migrations.AddField(
            model_name='settings',
            name='catalog_special_order',
            field=models.CharField(choices=[('banner_first', '\u0411\u0430\u043d\u043d\u0435\u0440, \u0442\u0435\u043a\u0441\u0442'), ('text_first', '\u0422\u0435\u043a\u0441\u0442, \u0431\u0430\u043d\u043d\u0435\u0440')], default='banner_first', max_length=15, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='catalog_special_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441 \u0430\u043a\u0446\u0438\u044f\u043c\u0438'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='catalog_special_text_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441 \u0430\u043a\u0446\u0438\u044f\u043c\u0438'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='catalog_special_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441 \u0430\u043a\u0446\u0438\u044f\u043c\u0438'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='catalog_special_text_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441 \u0430\u043a\u0446\u0438\u044f\u043c\u0438'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='catalog_special_text_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441 \u0430\u043a\u0446\u0438\u044f\u043c\u0438'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='catalog_special_text_it',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441 \u0430\u043a\u0446\u0438\u044f\u043c\u0438'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='catalog_special_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441 \u0430\u043a\u0446\u0438\u044f\u043c\u0438'),
        ),
    ]
