# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-01-25 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_settings_whatsapp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='percent_marketplays',
            field=models.IntegerField(blank=True, default=20, null=True, verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u043d\u0430 \u043a\u043e\u0442\u043e\u0440\u044b\u0439 \u0443\u0432\u0435\u043b\u0438\u0447\u0438\u0442\u044c \u0446\u0435\u043d\u0443 \u0434\u043b\u044f \u043c\u0430\u0440\u043a\u0435\u0442\u043f\u043b\u0435\u0439\u0441'),
        ),
    ]
