# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-05-23 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_social_widgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='title_mailing',
            field=models.CharField(default='', max_length=255, verbose_name='Title \u0434\u043b\u044f mailing'),
        ),
    ]
