# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-05-24 07:14
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_settings_title_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='mailing_banner',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='b/mailing/', verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440 \u0432 mailing'),
        ),
    ]
