# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-05-24 13:46
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_settings_mailing_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='mailing_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
