# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-02-02 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_settings_mailing_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='four_products_free',
            field=models.BooleanField(default=False, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u0430\u043a\u0446\u0438\u044e "4-\u0439 \u0442\u043e\u0432\u0430\u0440 \u0431\u0435\u0441\u043f\u043b\u0430\u0442\u043d\u043e"'),
        ),
    ]
