# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-02-20 12:09
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_settings_four_products_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='catalog_special_banner_mobil',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='b/catalog/', verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440 \u0441 \u0430\u043a\u0446\u0438\u044f\u043c\u0438 \u043d\u0430 \u043c\u043e\u0431\u0438\u043b\u043a\u0443'),
        ),
    ]
