# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-05-28 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0023_settings_catalog_special_banner_mobil'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='instagram',
            field=models.CharField(default='https://www.instagram.com/bikini_mini_ivanovskaya/', max_length=127, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 Instagram'),
        ),
    ]
