# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-07-24 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_settings_instagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='instagram',
        ),
    ]
