# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='accepting_to',
            field=models.DateField(blank=True, null=True, verbose_name='\u041a\u043e\u043d\u0435\u0446 \u043f\u0440\u0438\u0435\u043c\u0430 \u0437\u0430\u044f\u0432\u043e\u043a'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='list_cover',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='contests/covers/', verbose_name='\u041e\u0431\u043b\u043e\u0436\u043a\u0430 \u0432 \u0441\u043f\u0438\u0441\u043a\u0435 (\u0432\u0435\u0440\u0442\u0438\u043a\u0430\u043b\u044c\u043d\u0430\u044f)'),
        ),
    ]
