# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20180120_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contests.Contest', verbose_name='\u041a\u043e\u043d\u043a\u0443\u0440\u0441'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='contests_participants', to='catalog.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests_participants', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u0440\u043e\u0444\u0438\u043b\u044c'),
        ),
    ]
