# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20180120_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantphoto',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='contests.Participant', verbose_name='\u0423\u0447\u0430\u0441\u0442\u043d\u0438\u043a'),
        ),
    ]
