# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20180120_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestTitleLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=255, verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430')),
                ('line_ru', models.CharField(max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430')),
                ('line_en', models.CharField(max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430')),
                ('line_de', models.CharField(max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430')),
                ('line_fr', models.CharField(max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430')),
                ('line_it', models.CharField(max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430')),
                ('line_es', models.CharField(max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430')),
                ('big', models.BooleanField(default=False, verbose_name='\u041a\u0440\u0443\u043f\u043d\u044b\u0439 \u0448\u0440\u0438\u0444\u0442?')),
                ('order', models.IntegerField(default=10, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
            ],
            options={
                'ordering': ['order', 'id'],
                'verbose_name': '\u0441\u0442\u0440\u043e\u043a\u0430',
                'verbose_name_plural': '\u0441\u0442\u0440\u043e\u043a\u0438 \u0432 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u0435',
            },
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['status', '-published_dt'], 'verbose_name': '\u043a\u043e\u043d\u043a\u0443\u0440\u0441', 'verbose_name_plural': '\u043a\u043e\u043d\u043a\u0443\u0440\u0441\u044b'},
        ),
        migrations.AddField(
            model_name='contesttitleline',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_lines', to='contests.Contest', verbose_name='\u041a\u043e\u043d\u043a\u0443\u0440\u0441'),
        ),
    ]
