# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-19 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('lk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='building',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='\u0421\u0442\u0440\u043e\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.City', verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Country', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='profile',
            name='flat',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='\u041a\u0432\u0430\u0440\u0442\u0438\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='profile',
            name='house',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='\u0414\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='profile',
            name='housing',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='\u041a\u043e\u0440\u043f\u0443\u0441'),
        ),
        migrations.AddField(
            model_name='profile',
            name='index',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='\u0418\u043d\u0434\u0435\u043a\u0441'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=511, verbose_name='\u0424\u0418\u041e'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0439 \u0442\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='\u0423\u043b\u0438\u0446\u0430'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u043d \u043d\u0430 \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0443'),
        ),
    ]
