# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-19 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_photo'),
        ('lk', '0002_auto_20171019_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desired_products',
            field=models.ManyToManyField(blank=True, to='catalog.Product', verbose_name='\u0416\u0435\u043b\u0430\u0435\u043c\u044b\u0435 \u0442\u043e\u0432\u0430\u0440\u044b'),
        ),
    ]
