# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0003_profile_desired_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0424\u0418\u041e'),
        ),
    ]
