# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0004_auto_20171229_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='building',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='house',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='housing',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='index',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=511, null=True, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u0438\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
    ]
