# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0005_auto_20171229_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discount_code',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='discount_used',
            field=models.BooleanField(default=False),
        ),
    ]
