# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 12:50
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_specialoffer'),
        ('lk', '0006_auto_20180115_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='\u0426\u0435\u043d\u0430, \u0440\u0443\u0431.')),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='catalog.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='desired_products',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u0440\u043e\u0444\u0438\u043b\u044c'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set([('profile', 'product')]),
        ),
    ]
