# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0007_auto_20180128_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fb_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fb_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gp_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google+ ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gp_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google+ link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gp_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google+ name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ig_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ig_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ig_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VK ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VK link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='VK name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='discount_code',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='\u041a\u043e\u0434 \u0441\u043a\u0438\u0434\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='discount_used',
            field=models.BooleanField(default=False, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0430?'),
        ),
    ]
