# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0008_auto_20180202_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_password',
            field=models.BooleanField(default=True),
        ),
    ]
