# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 04:33
from __future__ import unicode_literals

from django.db import migrations


def remove_wishlist_items(apps, schema_editor):
    WishListItem = apps.get_model('lk', 'WishListItem')
    WishListItem.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0009_profile_has_password'),
    ]

    operations = [
        migrations.RunPython(remove_wishlist_items, reverse_code=migrations.RunPython.noop),
    ]
