# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_h1'),
        ('lk', '0010_remove_old_wishlist_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='catalog.ProductOption', verbose_name='\u0412\u0430\u0440\u0438\u0430\u043d\u0442'),
            preserve_default=False,
        ),
    ]
