# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0012_auto_20180212_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='\u0441\u043d\u0438\u043c\u0438\u0442\u0435 \u0433\u0430\u043b\u043a\u0443, \u0447\u0442\u043e\u0431\u044b \u0437\u0430\u0431\u043b\u043e\u043a\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u044e\u0437\u0435\u0440\u0430', verbose_name='\u0410\u043a\u0442\u0438\u0432\u0435\u043d?'),
        ),
    ]
