# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 16:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0013_auto_20180225_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='extra_products',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='hash',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set([]),
        ),
    ]
