# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 16:11
from __future__ import unicode_literals

from django.db import migrations

from apps.hash_utils import make_hash_from_cartitem


def set_hashes(apps, schema_editor):
    WishListItem = apps.get_model('lk', 'WishListItem')
    for obj in WishListItem.objects.all().order_by('-id'):
        obj.hash = make_hash_from_cartitem(obj.attrs, obj.extra_products)
        obj.save()
        print obj.id, obj.hash


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0014_wishlistitem_hash'),
    ]

    operations = [
        migrations.RunPython(set_hashes, reverse_code=migrations.RunPython.noop),
    ]
