# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0015_wishlistitem_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='price',
            new_name='price_rub',
        ),
    ]
