# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0016_rub_eur_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='\u0426\u0435\u043d\u0430, eur.'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='\u0426\u0435\u043d\u0430, usd.'),
        ),
    ]
