# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 14:05
from __future__ import unicode_literals

from django.db import migrations


def save_currency_prices(apps, schema_editor):
    WishlistItem = apps.get_model('lk', 'WishlistItem')

    print; print; print 'WishlistItem...'
    for obj in WishlistItem.objects.select_related('product', 'option').prefetch_related('product__extra_options').order_by('-id'):
        obj.save()
        print obj.id, obj.price_rub, obj.price_eur, obj.price_usd

class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0017_rub_eur_usd'),
    ]

    operations = [
        migrations.RunPython(save_currency_prices, reverse_code=migrations.RunPython.noop),
    ]
