# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-30 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0018_rub_eur_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Login hash'),
        ),
    ]
