# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-05 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0020_profile_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ym_client_id',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u043f\u043e\u0441\u0435\u0442\u0438\u0442\u0435\u043b\u044f'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ym_source',
            field=models.CharField(blank=True, choices=[('organic', '\u041f\u0435\u0440\u0435\u0445\u043e\u0434\u044b \u0438\u0437 \u043f\u043e\u0438\u0441\u043a\u043e\u0432\u044b\u0445 \u0441\u0438\u0441\u0442\u0435\u043c'), ('social', '\u041f\u0435\u0440\u0435\u0445\u043e\u0434\u044b \u0438\u0437 \u0441\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0445 \u0441\u0435\u0442\u0435\u0439'), ('ad', '\u041f\u0435\u0440\u0435\u0445\u043e\u0434\u044b \u043f\u043e \u0440\u0435\u043a\u043b\u0430\u043c\u0435'), ('direct', '\u041f\u0440\u044f\u043c\u044b\u0435 \u0437\u0430\u0445\u043e\u0434\u044b'), ('internal', '\u0412\u043d\u0443\u0442\u0440\u0435\u043d\u043d\u0438\u0435 \u043f\u0435\u0440\u0435\u0445\u043e\u0434\u044b'), ('referral', '\u041f\u0435\u0440\u0435\u0445\u043e\u0434\u044b \u043f\u043e \u0441\u0441\u044b\u043b\u043a\u0430\u043c \u043d\u0430 \u0441\u0430\u0439\u0442\u0430\u0445'), ('saved', '\u041f\u0435\u0440\u0435\u0445\u043e\u0434\u044b \u0441 \u0441\u043e\u0445\u0440\u0430\u043d\u0451\u043d\u043d\u044b\u0445 \u0441\u0442\u0440\u0430\u043d\u0438\u0446')], max_length=15, null=True, verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a \u0442\u0440\u0430\u0444\u0438\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ym_source_detailed',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a \u0442\u0440\u0430\u0444\u0438\u043a\u0430 (\u0434\u0435\u0442\u0430\u043b\u044c\u043d\u043e)'),
        ),
    ]
