# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-05 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0021_yandex_metrika'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orders_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
