# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-05 16:11
from __future__ import unicode_literals

from django.db import migrations


def set_orders_num(apps, schema_editor):
    Profile = apps.get_model('lk', 'Profile')

    print; print; print 'setting orders_num...'
    print 'id\tnum / all'
    for obj in Profile.objects.prefetch_related('cart_set').order_by('-id'):
        obj.orders_num = obj.cart_set.filter(checked_out=True).count()
        obj.save()
        print obj.id, '\t', obj.orders_num, '/', obj.cart_set.all().count()


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0022_profile_orders_num'),
    ]

    operations = [
        migrations.RunPython(set_orders_num, reverse_code=migrations.RunPython.noop),
    ]
