# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-22 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0023_profile_orders_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lang',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en'), ('de', 'de'), ('fr', 'fr'), ('it', 'it'), ('es', 'es')], default='ru', max_length=3, verbose_name='\u042f\u0437\u044b\u043a'),
        ),
    ]
