# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-22 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0024_profile_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mailchimp_address',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mailchimp_all_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mailchimp_city',
            field=models.CharField(blank=True, editable=False, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mailchimp_country_title',
            field=models.CharField(blank=True, editable=False, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mailchimp_lang',
            field=models.CharField(blank=True, editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mailchimp_name',
            field=models.CharField(blank=True, editable=False, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mailchimp_phone',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mailchimp_subscribed_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mailchimp_tried_to_subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='mailchimp_unsubscribed_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='old_subscription',
            field=models.BooleanField(default=False, verbose_name='Previous \u041f\u043e\u0434\u043f\u0438\u0441\u0430\u043d \u043d\u0430 \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0443'),
        ),
    ]
