# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-05-23 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0025_mailchimp_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511, verbose_name='\u041f\u043e\u043b\u043d\u043e\u0435 \u0438\u043c\u044f')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='lang',
            field=models.CharField(choices=[('ru', 'ru'), ('en', 'en'), ('de', 'de'), ('es', 'es'), ('fr', 'fr'), ('it', 'it')], default='ru', max_length=3, verbose_name='\u042f\u0437\u044b\u043a'),
        ),
    ]
