# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-05-23 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0026_auto_20220523_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['id'], 'verbose_name': '\u0420\u0430\u0441\u0441\u044b\u043b\u043a\u0430', 'verbose_name_plural': '\u0420\u0430\u0441\u0441\u044b\u043b\u043a\u0438'},
        ),
    ]
