# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-05-23 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0027_auto_20220523_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='name',
            field=models.CharField(max_length=511, verbose_name='\u0418\u043c\u044f \u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
        ),
    ]
