# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-05-28 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0029_auto_20220524_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
    ]
