# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-19 17:13
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='', upload_to='catalog/products/', verbose_name='\u0424\u043e\u0442\u043e'),
            preserve_default=False,
        ),
    ]
