# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-25 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sex', 'order', 'id'], 'verbose_name': '\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f', 'verbose_name_plural': '\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'},
        ),
        migrations.AlterField(
            model_name='category',
            name='sex',
            field=models.CharField(choices=[('male', '\u041c\u0443\u0436\u0447\u0438\u043d\u0430\u043c'), ('female', '\u0416\u0435\u043d\u0449\u0438\u043d\u0430\u043c')], default='female', max_length=7, verbose_name='\u041f\u043e\u043b'),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_products',
            field=models.ManyToManyField(blank=True, related_name='from_additional', to='catalog.Product', verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0442\u043e\u0432\u0430\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='product',
            name='also_products',
            field=models.ManyToManyField(blank=True, related_name='from_also', to='catalog.Product', verbose_name='\u0421 \u044d\u0442\u0438\u043c \u0442\u043e\u0432\u0430\u0440\u043e\u043c \u0442\u0430\u043a\u0436\u0435 \u043f\u043e\u043a\u0443\u043f\u0430\u044e\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='associated_products',
            field=models.ManyToManyField(blank=True, related_name='from_associated', to='catalog.Product', verbose_name='\u0421\u043e\u043f\u0443\u0442\u0441\u0442\u0432\u0443\u044e\u0449\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('default', '\u0442\u043e\u0432\u0430\u0440'), ('additional', '\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439 \u0442\u043e\u0432\u0430\u0440'), ('certificate', '\u043f\u043e\u0434\u0430\u0440\u043e\u0447\u043d\u044b\u0439 \u0441\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442')], default='default', max_length=15, verbose_name='\u0422\u0438\u043f \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
    ]
