# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 06:24
from __future__ import unicode_literals

import colorfield.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_new_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_de', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_it', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('vendor_code', models.CharField(blank=True, max_length=255, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='catalog/products/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('price_rub', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430, \u0440\u0443\u0431.')),
                ('price_eur', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430, eur.')),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430, usd.')),
                ('show', models.BooleanField(default=True, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439 \u0442\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0442\u043e\u0432\u0430\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_de', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_it', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(help_text='\u0430\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438\u0435 \u0431\u0443\u043a\u0432\u044b \u0438 \u0446\u0438\u0444\u0440\u044b', unique=True, verbose_name='\u0412 URL')),
                ('attr_type', models.CharField(choices=[('color', '\u0446\u0432\u0435\u0442'), ('size', '\u0440\u0430\u0437\u043c\u0435\u0440'), ('style', '\u0444\u0430\u0441\u043e\u043d')], max_length=7, verbose_name='\u0422\u0438\u043f')),
                ('order', models.IntegerField(default=10, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('display_type', models.CharField(choices=[('home', '\u0432 \u043e\u0431\u0449\u0435\u043c \u0444\u0438\u043b\u044c\u0442\u0440\u0435'), ('category', '\u0432 \u0444\u0438\u043b\u044c\u0442\u0440\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'), ('product', '\u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0442\u043e\u0432\u0430\u0440\u0430'), ('off', '\u043e\u0442\u043a\u043b.')], max_length=15, verbose_name='\u0422\u0438\u043f \u043f\u043e\u043a\u0430\u0437\u0430')),
            ],
            options={
                'ordering': ['order', 'id'],
                'verbose_name': '\u0430\u0442\u0440\u0438\u0431\u0443\u0442',
                'verbose_name_plural': '\u0430\u0442\u0440\u0438\u0431\u0443\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_de', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_it', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('picture', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='catalog/attributes/', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('color', colorfield.fields.ColorField(blank=True, max_length=18)),
                ('order', models.IntegerField(default=10, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.Attribute', verbose_name='\u0410\u0442\u0440\u0438\u0431\u0443\u0442')),
            ],
            options={
                'ordering': ['order', 'id'],
                'verbose_name': '\u0432\u0430\u0440\u0438\u0430\u043d\u0442',
                'verbose_name_plural': '\u0432\u0430\u0440\u0438\u0430\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_de', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_it', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('vendor_code', models.CharField(blank=True, max_length=255, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b')),
                ('price_rub', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430, \u0440\u0443\u0431.')),
                ('price_eur', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430, eur.')),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430, usd.')),
                ('show', models.BooleanField(default=True, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
            ],
            options={
                'ordering': ['price_rub', 'id'],
                'verbose_name': '\u0441\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442',
                'verbose_name_plural': '\u0441\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u044b',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='attrs',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_products',
            field=models.ManyToManyField(blank=True, related_name='from_additional', to='catalog.AdditionalProduct', verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0442\u043e\u0432\u0430\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.SmallIntegerField(default=5, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435'),
        ),
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='categories', to='catalog.Attribute', verbose_name='\u0410\u0442\u0440\u0438\u0431\u0443\u0442\u044b'),
        ),
    ]
