# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 03:08
from __future__ import unicode_literals

from django.db import migrations


def set_display_type(apps, schema_editor):
    Attribute = apps.get_model('catalog', 'Attribute')
    Attribute.objects.all().update(display_type=3)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20171107_0924'),
    ]

    operations = [
        migrations.RunPython(set_display_type, reverse_code=migrations.RunPython.noop),
    ]
