# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 03:10
from __future__ import unicode_literals

import colorfield.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_updates1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_de', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_it', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('vendor_code', models.CharField(blank=True, max_length=255, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b')),
                ('price_rub', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430, \u0440\u0443\u0431.')),
                ('price_eur', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430, eur.')),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430, usd.')),
                ('in_stock', models.SmallIntegerField(default=5, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435')),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u0432\u0430\u0440\u0438\u0430\u043d\u0442',
                'verbose_name_plural': '\u0432\u0430\u0440\u0438\u0430\u043d\u0442\u044b \u0442\u043e\u0432\u0430\u0440\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', easy_thumbnails.fields.ThumbnailerImageField(upload_to='catalog/products/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u0432\u0430\u0440\u0438\u0430\u043d\u0442',
                'verbose_name_plural': '\u0432\u0430\u0440\u0438\u0430\u043d\u0442\u044b \u0442\u043e\u0432\u0430\u0440\u043e\u0432',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='attrs',
        ),
        migrations.AddField(
            model_name='attribute',
            name='position',
            field=models.CharField(choices=[('all', '---'), ('bottom', '\u043d\u0438\u0437'), ('top', '\u0432\u0435\u0440\u0445')], default='all', max_length=7, verbose_name='\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='display_type',
            field=models.SmallIntegerField(choices=[(3, '\u0432 \u043e\u0431\u0449\u0435\u043c \u0444\u0438\u043b\u044c\u0442\u0440\u0435'), (2, '\u0432 \u0444\u0438\u043b\u044c\u0442\u0440\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'), (1, '\u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0442\u043e\u0432\u0430\u0440\u0430'), (0, '\u043e\u0442\u043a\u043b.')], default=3, verbose_name='\u0422\u0438\u043f \u043f\u043e\u043a\u0430\u0437\u0430'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='slug',
            field=models.SlugField(help_text='\u0443\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435; \u043f\u0440\u0438\u043d\u0438\u043c\u0430\u044e\u0442\u0441\u044f \u0430\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438\u0435 \u0431\u0443\u043a\u0432\u044b, \u0446\u0438\u0444\u0440\u044b \u0438 \u0441\u0438\u043c\u0432\u043e\u043b "_"\n                                                  <br><br>\u043f\u0440\u0438\u043c\u0435\u0440\u044b:<br>- color<br>- top_w<br>- bottom_size', unique=True, verbose_name='\u0412 URL'),
        ),
        migrations.AlterField(
            model_name='attributeoption',
            name='color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, verbose_name='\u0426\u0432\u0435\u0442'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
    ]
