# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 03:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_updates2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attrs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
