# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_updates3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalproduct',
            options={'ordering': ['-id'], 'verbose_name': '\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439 \u0442\u043e\u0432\u0430\u0440', 'verbose_name_plural': '\u0442\u043e\u0432\u0430\u0440\u044b: \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0442\u043e\u0432\u0430\u0440\u044b'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['price_rub', 'id'], 'verbose_name': '\u0441\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442', 'verbose_name_plural': '\u0442\u043e\u0432\u0430\u0440\u044b: \u0441\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ['id'], 'verbose_name': '\u0432\u0430\u0440\u0438\u0430\u043d\u0442', 'verbose_name_plural': '\u0432\u0430\u0440\u0438\u0430\u043d\u0442\u044b \u0442\u043e\u0432\u0430\u0440\u0430'},
        ),
        migrations.AlterModelOptions(
            name='productphoto',
            options={'ordering': ['id'], 'verbose_name': '\u0444\u043e\u0442\u043e', 'verbose_name_plural': '\u0444\u043e\u0442\u043e'},
        ),
        migrations.AddField(
            model_name='attribute',
            name='admin_title',
            field=models.CharField(default='-', max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u0432 \u0430\u0434\u043c\u0438\u043d\u043a\u0435)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attr_type',
            field=models.CharField(choices=[('color', '\u0446\u0432\u0435\u0442'), ('size', '\u0440\u0430\u0437\u043c\u0435\u0440'), ('style', '\u0444\u0430\u0441\u043e\u043d'), ('text', '\u0442\u0435\u043a\u0441\u0442')], max_length=7, verbose_name='\u0422\u0438\u043f'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='position',
            field=models.CharField(choices=[('all', '\u0432\u0441\u0435'), ('bottom', '\u043d\u0438\u0437'), ('top', '\u0432\u0435\u0440\u0445')], default='all', max_length=7, verbose_name='\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='title',
            field=models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u043d\u0430 \u0441\u0430\u0439\u0442\u0435)'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u043d\u0430 \u0441\u0430\u0439\u0442\u0435)'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u043d\u0430 \u0441\u0430\u0439\u0442\u0435)'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u043d\u0430 \u0441\u0430\u0439\u0442\u0435)'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u043d\u0430 \u0441\u0430\u0439\u0442\u0435)'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='title_it',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u043d\u0430 \u0441\u0430\u0439\u0442\u0435)'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u043d\u0430 \u0441\u0430\u0439\u0442\u0435)'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='\u043e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u0446\u0435\u043d\u044b \u043f\u0443\u0441\u0442\u044b\u043c\u0438, \u0447\u0442\u043e\u0431\u044b \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0446\u0435\u043d\u0443 \u0440\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u043e\u0433\u043e \u0442\u043e\u0432\u0430\u0440\u0430', max_digits=9, verbose_name='\u0426\u0435\u043d\u0430, usd.'),
        ),
    ]
