# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 02:31
from __future__ import unicode_literals

from django.db import migrations


def set_admin_title(apps, schema_editor):
    from django.db.models import F
    Attribute = apps.get_model('catalog', 'Attribute')
    Attribute.objects.update(admin_title=F('title'))


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_attribute_admin_title'),
    ]

    operations = [
        migrations.RunPython(set_admin_title, reverse_code=migrations.RunPython.noop),
    ]
