# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_attribute_neighbor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['-category', 'order', 'id'], 'verbose_name': '\u0430\u0442\u0440\u0438\u0431\u0443\u0442', 'verbose_name_plural': '\u0430\u0442\u0440\u0438\u0431\u0443\u0442\u044b'},
        ),
        migrations.AddField(
            model_name='attribute',
            name='add_to_price',
            field=models.BooleanField(default=False, help_text='\u0434\u043b\u044f \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0445 \u0430\u0442\u0440\u0438\u0431\u0443\u0442\u043e\u0432', verbose_name='\u041f\u0440\u0438\u0431\u0430\u0432\u043b\u044f\u0442\u044c \u043a \u0446\u0435\u043d\u0435'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.CharField(choices=[('primary', '\u043e\u0441\u043d\u043e\u0432\u043d\u043e\u0439'), ('extra', '\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439')], default='primary', max_length=7, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
            preserve_default=False,
        ),
    ]
