# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 16:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20171119_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u0432 \u0430\u0434\u043c\u0438\u043d\u043a\u0435)')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u043d\u0430 \u0441\u0430\u0439\u0442\u0435)')),
                ('slug', models.SlugField(help_text='\u0443\u043d\u0438\u043a\u0430\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435; \u043f\u0440\u0438\u043d\u0438\u043c\u0430\u044e\u0442\u0441\u044f \u0430\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438\u0435 \u0431\u0443\u043a\u0432\u044b, \u0446\u0438\u0444\u0440\u044b \u0438 \u0441\u0438\u043c\u0432\u043e\u043b "_"\n                                                  <br><br>\u043f\u0440\u0438\u043c\u0435\u0440\u044b:<br>- color<br>- top_w<br>- bottom_size', unique=True, verbose_name='\u0412 URL')),
                ('order', models.IntegerField(default=10, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
            ],
        ),
        migrations.CreateModel(
            name='ProductExtraOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('vendor_code', models.CharField(blank=True, max_length=255, verbose_name='\u0410\u0440\u0442\u0438\u043a\u0443\u043b')),
                ('price_rub', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430, \u0440\u0443\u0431.')),
                ('price_eur', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430, eur.')),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430, usd.')),
                ('in_stock', models.SmallIntegerField(default=5, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435')),
                ('attrs', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('extra_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_options', to='catalog.ExtraProduct', verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439 \u0442\u043e\u0432\u0430\u0440')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u0432\u0430\u0440\u0438\u0430\u043d\u0442',
                'verbose_name_plural': '\u0432\u0430\u0440\u0438\u0430\u043d\u0442\u044b \u0442\u043e\u0432\u0430\u0440\u0430',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='products', to='catalog.Attribute', verbose_name='\u0410\u0442\u0440\u0438\u0431\u0443\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='category',
            field=models.CharField(choices=[('primary', '\u043e\u0441\u043d\u043e\u0432\u043d\u044b\u0435'), ('extra', '\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435')], max_length=7, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='productextraoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_options', to='catalog.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
        migrations.AddField(
            model_name='extraproduct',
            name='attributes',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='extra_products', to='catalog.Attribute', verbose_name='\u0410\u0442\u0440\u0438\u0431\u0443\u0442\u044b'),
        ),
        migrations.AlterUniqueTogether(
            name='productextraoption',
            unique_together=set([('product', 'extra_product')]),
        ),
    ]
