# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 16:16
from __future__ import unicode_literals

from django.db import migrations


def set_product_attributes(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    for obj in Product.objects.all():
        obj.attributes = obj.category.attributes.all()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_extra_stuff'),
    ]

    operations = [
        migrations.RunPython(set_product_attributes, reverse_code=migrations.RunPython.noop),
    ]
