# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_extra_stuff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extraproduct',
            options={'ordering': ['order', 'id'], 'verbose_name': '\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439 \u0442\u043e\u0432\u0430\u0440', 'verbose_name_plural': '\u0430\u0442\u0440\u0438\u0431\u0443\u0442\u044b: \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0442\u043e\u0432\u0430\u0440\u044b'},
        ),
        migrations.AddField(
            model_name='extraproduct',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u043d\u0430 \u0441\u0430\u0439\u0442\u0435)'),
        ),
        migrations.AddField(
            model_name='extraproduct',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u043d\u0430 \u0441\u0430\u0439\u0442\u0435)'),
        ),
        migrations.AddField(
            model_name='extraproduct',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u043d\u0430 \u0441\u0430\u0439\u0442\u0435)'),
        ),
        migrations.AddField(
            model_name='extraproduct',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u043d\u0430 \u0441\u0430\u0439\u0442\u0435)'),
        ),
        migrations.AddField(
            model_name='extraproduct',
            name='title_it',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u043d\u0430 \u0441\u0430\u0439\u0442\u0435)'),
        ),
        migrations.AddField(
            model_name='extraproduct',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 (\u043d\u0430 \u0441\u0430\u0439\u0442\u0435)'),
        ),
    ]
