# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_extra_stuff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productextraoption',
            options={'ordering': ['id'], 'verbose_name': '\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439 \u0442\u043e\u0432\u0430\u0440', 'verbose_name_plural': '\u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u0442\u043e\u0432\u0430\u0440\u044b'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='boo', max_length=127, verbose_name='\u0412 URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug_de',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_es',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_fr',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_it',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_ru',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='woo', max_length=127, verbose_name='\u0412 URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug_de',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_es',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_fr',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_it',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_ru',
            field=models.SlugField(max_length=127, null=True, verbose_name='\u0412 URL'),
        ),
    ]
