# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 00:48
from __future__ import unicode_literals

from django.db import migrations


def set_slug(apps, schema_editor):
    """
    FROM: https://raphaelbeck.wordpress.com/2011/04/16/how-to-translate-slug-with-django-modeltranslation/
    """
    # from pytils.translit import slugify as ru_slugify
    # from django.utils.text import slugify
    from uuslug import slugify
    from django.conf import settings

    Category = apps.get_model('catalog', 'Category')
    Product = apps.get_model('catalog', 'Product')

    for model in [Category, Product]:
        for obj in model.objects.all():
            for lang_code, lang_verbose in settings.LANGUAGES:
                setattr(obj, 'slug_%s' % lang_code, slugify(getattr(obj, 'title_%s' % lang_code) or obj.title_ru)[:127])
            setattr(obj, 'slug', getattr(obj, 'slug_ru'))
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_slug'),
    ]

    operations = [
        migrations.RunPython(set_slug, reverse_code=migrations.RunPython.noop),
    ]
