# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('sex', 'slug')]),
        ),
    ]
