# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftWrapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_rub', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430, \u0440\u0443\u0431.')),
                ('price_eur', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430, eur.')),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430, usd.')),
            ],
            options={
                'verbose_name': '\u043f\u043e\u0434\u0430\u0440\u043e\u0447\u043d\u0430\u044f \u0443\u043f\u0430\u043a\u043e\u0432\u043a\u0430',
                'verbose_name_plural': '\u043f\u043e\u0434\u0430\u0440\u043e\u0447\u043d\u0430\u044f \u0443\u043f\u0430\u043a\u043e\u0432\u043a\u0430',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='sex',
            field=models.CharField(choices=[('female', '\u0416\u0435\u043d\u0449\u0438\u043d\u0430\u043c'), ('male', '\u041c\u0443\u0436\u0447\u0438\u043d\u0430\u043c')], default='female', max_length=7, verbose_name='\u041f\u043e\u043b'),
        ),
    ]
