# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('catalog', '0020_auto_20171128_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_f',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='photo_f',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='\u0424\u043e\u0442\u043e'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='title',
            field=models.CharField(blank=True, help_text='\u0434\u043b\u044f \u043f\u043e\u043a\u0430\u0437\u0430 \u0432 \u0430\u0434\u043c\u0438\u043d\u043a\u0435', max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
