# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 16:26
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20171203_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text_de',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text_es',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text_fr',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text_it',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
