# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 07:42
from __future__ import unicode_literals

from django.db import migrations


def set_product_categories(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    for obj in Product.objects.all():
        obj.categories.add(obj.category)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_product_categories'),
    ]

    operations = [
        migrations.RunPython(set_product_categories, reverse_code=migrations.RunPython.noop),
    ]
