# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 05:44
from __future__ import unicode_literals

from django.db import migrations, models


def set_order(apps, schema_editor):
    """
    FROM: http://django-admin-sortable2.readthedocs.io/en/latest/usage.html#initial-data
    """
    Product = apps.get_model('catalog', 'Product')

    order = 0
    for obj in Product.objects.all().order_by('-id'):
        order += 1
        obj.order = order
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_product_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', '-id'], 'verbose_name': '\u0442\u043e\u0432\u0430\u0440', 'verbose_name_plural': '\u0442\u043e\u0432\u0430\u0440\u044b'},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='&nbsp;'),
        ),
        migrations.RunPython(set_order, reverse_code=migrations.RunPython.noop),
    ]
