# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def clear_neighbors(apps, schema_editor):
    Attribute = apps.get_model('catalog', 'Attribute')
    Attribute.objects.exclude(attr_type='style').update(neighbor=None)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='neighbor',
            field=models.ForeignKey(blank=True, help_text='\u0432\u044b\u0432\u043e\u0434\u0438\u0442\u0441\u044f \u0440\u044f\u0434\u043e\u043c \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0442\u043e\u0432\u0430\u0440\u0430', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_neighbor', to='catalog.Attribute', verbose_name='\u0421\u043e\u0441\u0435\u0434\u043d\u0438\u0439 \u0430\u0442\u0440\u0438\u0431\u0443\u0442'),
        ),
        migrations.RunPython(clear_neighbors, reverse_code=migrations.RunPython.noop),
    ]
