# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20171217_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='&nbsp;&nbsp;&nbsp;&nbsp;'),
        ),
    ]
