# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 20:55
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20171226_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='seo_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_text_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_text_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_text_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_text_it',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_text_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_text_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_text_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_text_it',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='SEO-\u0442\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text_it',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
