# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_ckeditor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveSmallIntegerField(default=50, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430, %')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0430\u043a\u0442\u0438\u0432\u043d\u0430?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='catalog.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440')),
            ],
            options={
                'verbose_name': '\u0441\u043f\u0435\u0446.\u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0441\u043f\u0435\u0446.\u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f',
            },
        ),
    ]
