# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-05 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_remove_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productextraoption',
            name='in_stock',
            field=models.SmallIntegerField(default=100, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='in_stock',
            field=models.SmallIntegerField(default=100, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043d\u0430 \u0441\u043a\u043b\u0430\u0434\u0435'),
        ),
    ]
