# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-27 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_alter_in_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productphoto',
            options={'ordering': ['order', 'id'], 'verbose_name': '\u0444\u043e\u0442\u043e', 'verbose_name_plural': '\u0444\u043e\u0442\u043e'},
        ),
        migrations.AddField(
            model_name='productphoto',
            name='order',
            field=models.IntegerField(default=10, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a'),
        ),
    ]
