# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-30 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_productphoto_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOfferCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='\u0434\u043b\u044f \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u044f \u0432 \u0430\u0434\u043c\u0438\u043d\u043a\u0435', max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('price_rub', models.DecimalField(decimal_places=2, default=0, max_digits=9, unique=True, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u043e\u0442, \u0440\u0443\u0431.')),
                ('price_eur', models.DecimalField(decimal_places=2, default=0, help_text='\u0437\u0430\u043f\u043e\u043b\u043d\u0438\u0442\u0441\u044f \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438', max_digits=9, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u043e\u0442, eur.')),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, help_text='\u0437\u0430\u043f\u043e\u043b\u043d\u0438\u0442\u0441\u044f \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438', max_digits=9, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u043e\u0442, usd.')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u043e?')),
            ],
            options={
                'ordering': ['-is_active', 'price_rub'],
                'verbose_name': '\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
                'verbose_name_plural': '\u0441\u043f\u0435\u0446.\u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f: \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f',
            },
        ),
        migrations.AlterModelOptions(
            name='specialoffer',
            options={'verbose_name': '\u0441\u043f\u0435\u0446.\u0442\u043e\u0432\u0430\u0440', 'verbose_name_plural': '\u0441\u043f\u0435\u0446.\u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f: \u0442\u043e\u0432\u0430\u0440\u044b'},
        ),
    ]
