# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-30 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_specialoffercategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialoffercategory',
            options={'ordering': ['-is_active', 'price_rub'], 'verbose_name': '\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438', 'verbose_name_plural': '\u0441\u043f\u0435\u0446.\u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f: \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'},
        ),
    ]
