# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-30 01:34
from __future__ import unicode_literals

from django.db import migrations


def load_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', '20181130_special_offer_category.json')


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_specialoffercategory'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=migrations.RunPython.noop),
    ]
