# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-30 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_load_special_offer_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialoffer',
            options={'ordering': ['-is_active', 'category', 'id'], 'verbose_name': '\u0441\u043f\u0435\u0446.\u0442\u043e\u0432\u0430\u0440', 'verbose_name_plural': '\u0441\u043f\u0435\u0446.\u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f: \u0442\u043e\u0432\u0430\u0440\u044b'},
        ),
        migrations.AlterModelOptions(
            name='specialoffercategory',
            options={'ordering': ['-is_active', 'price_rub'], 'verbose_name': '\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f', 'verbose_name_plural': '\u0441\u043f\u0435\u0446.\u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0435\u043d\u0438\u044f: \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'},
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.SpecialOfferCategory', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='specialoffercategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u0430?'),
        ),
        migrations.AlterField(
            model_name='specialoffercategory',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u043e\u0442, eur.'),
        ),
        migrations.AlterField(
            model_name='specialoffercategory',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u043e\u0442, usd.'),
        ),
        #migrations.AlterUniqueTogether(
        #    name='specialoffer',
        #    unique_together=set([('category', 'product')]),
        #),
    ]
