# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-30 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_special_offer_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specialoffer',
            unique_together=set([('category', 'product')]),
        ),
    ]
