# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-28 00:16
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_product_tabs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttab',
            name='h1',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='h1_nsk',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='h1_sam',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='h1_sch',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='h1_smf',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='h1_spb',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='h1_svs',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_desc',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_desc_nsk',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_desc_sam',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_desc_sch',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_desc_smf',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_desc_spb',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_desc_svs',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_keyw',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_keyw_nsk',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_keyw_sam',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_keyw_sch',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_keyw_smf',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_keyw_spb',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_keyw_svs',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_title_nsk',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_title_sam',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_title_sch',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_title_smf',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_title_spb',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='meta_title_svs',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='seo_text',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='seo_text_nsk',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='seo_text_sam',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='seo_text_sch',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='seo_text_smf',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='seo_text_spb',
        ),
        migrations.RemoveField(
            model_name='producttab',
            name='seo_text_svs',
        ),
        migrations.AlterField(
            model_name='producttab',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='\u0442\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u0435\u0434 \u0441\u0435\u043a\u0446\u0438\u044f\u043c\u0438', verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='producttab',
            name='text_de',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='\u0442\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u0435\u0434 \u0441\u0435\u043a\u0446\u0438\u044f\u043c\u0438', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='producttab',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='\u0442\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u0435\u0434 \u0441\u0435\u043a\u0446\u0438\u044f\u043c\u0438', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='producttab',
            name='text_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='\u0442\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u0435\u0434 \u0441\u0435\u043a\u0446\u0438\u044f\u043c\u0438', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='producttab',
            name='text_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='\u0442\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u0435\u0434 \u0441\u0435\u043a\u0446\u0438\u044f\u043c\u0438', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='producttab',
            name='text_it',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='\u0442\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u0435\u0434 \u0441\u0435\u043a\u0446\u0438\u044f\u043c\u0438', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='producttab',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='\u0442\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u0435\u0434 \u0441\u0435\u043a\u0446\u0438\u044f\u043c\u0438', null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
