# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-01-19 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_category_is_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_at_yandex',
            field=models.BooleanField(default=True, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u0432 \u0444\u0438\u0434\u0435 \u042f\u043d\u0434\u0435\u043a\u0441'),
        ),
    ]
