# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-01-19 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_product_show_at_yandex'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_yandex',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0434\u043b\u044f \u042f\u043d\u0434\u0435\u043a\u0441\u0430'),
        ),
    ]
