# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-01-22 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_category_title_yandex'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ozon_category_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 Ozon'),
        ),
    ]
