# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-01-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0055_category_ozon_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ozone_type',
            field=models.CharField(blank=True, help_text='\u041d\u0443\u0436\u0435\u043d \u0434\u043b\u044f \u0442\u043e\u0433\u043e \u0447\u0442\u043e\u0431\u044b, \u0431\u043e\u043b\u0435\u0435 \u0442\u043e\u0447\u043d\u043e \u043f\u0435\u0440\u0435\u0434\u0430\u0442\u044c \u0442\u0438\u043f \u0442\u043e\u0432\u0430\u0440\u0430 \u0432 Ozon, \u0435\u0441\u043b\u0438 \u043d\u0435 \u0437\u0430\u043f\u043e\u043b\u0435\u043d\u043d\u043e, \u0442\u043e \u043f\u0435\u0440\u0434\u0430\u0435\u0442\u0441\u044f \u043d\u0430\u0437\u0430\u043d\u0438\u0435 \u043f\u0435\u0440\u0432\u043e\u0439 \u0440\u0443\u0431\u0440\u0438\u043a\u0438, \u043a\u043e\u0442\u043e\u0440\u043e\u0439 \u043f\u0440\u0438\u043d\u0430\u0434\u043b\u0435\u0436\u0438\u0442 \u0442\u043e\u0432\u0430\u0440.', max_length=255, null=True, verbose_name='\u0422\u0438\u043f Ozon'),
        ),
    ]
