# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-01-27 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_productphoto_color_ozon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ozone_ocpd',
            field=models.CharField(blank=True, help_text='\u0423\u043a\u0430\u0437\u0430\u0442\u044c \u0435\u0441\u043b\u0438 \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u043f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e \u043d\u0435 \u043f\u043e\u0434\u043e\u0448\u043b\u043e.', max_length=512, null=True, verbose_name='\u041e\u0437\u043e\u043d \u041a\u043e\u0434 \u041e\u041a\u041f\u0414/\u0422\u041d \u0412\u042d\u0414'),
        ),
    ]
