# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-02-01 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0060_auto_20220927_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='installment',
            field=models.BooleanField(default=False, verbose_name='\u0414\u043e\u0441\u0442\u0443\u043f\u043d\u0430 \u0440\u0430\u0441\u0441\u0440\u043e\u0447\u043a\u0430'),
        ),
    ]
