# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-06-29 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0061_product_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retailcrm',
            field=models.BooleanField(default=True, verbose_name='\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0432 retailcrm'),
        ),
    ]
