# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-09-16 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0062_product_retailcrm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '\u0427\u0435\u0440\u043d\u043e\u0432\u0438\u043a'), ('published', '\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d'), ('hidden', '\u0421\u043a\u0440\u044b\u0442')], default='draft', max_length=10, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('review_date', models.DateField(default=datetime.date.today, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u0437\u044b\u0432\u0430')),
                ('screenshot', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='reviews/', verbose_name='\u0421\u043a\u0440\u0438\u043d\u0448\u043e\u0442')),
                ('text', models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e\u0442\u0437\u044b\u0432\u0430')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='\u0417\u0430\u043a\u0440\u0435\u043f\u0438\u0442\u044c')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='\u0410\u0432\u0442\u043e\u0440')),
                ('original_url', models.URLField(blank=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u043e\u0440\u0438\u0433\u0438\u043d\u0430\u043b')),
                ('products', models.ManyToManyField(blank=True, related_name='reviews', to='catalog.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440\u044b')),
            ],
            options={
                'ordering': ['-is_pinned', '-review_date'],
                'verbose_name': '\u043e\u0442\u0437\u044b\u0432',
                'verbose_name_plural': '\u041e\u0442\u0437\u044b\u0432\u044b',
            },
        ),
    ]
