# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-25 04:39
from __future__ import unicode_literals

import apps.banners.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='\u0414\u043b\u044f \u043f\u043e\u043a\u0430\u0437\u0430 \u0432 \u0430\u0434\u043c\u0438\u043d\u043a\u0435 \u0438 \u0432 \u0430\u0442\u0440\u0438\u0431\u0443\u0442\u0430\u0445 alt \u0438 title', max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('title_ru', models.CharField(help_text='\u0414\u043b\u044f \u043f\u043e\u043a\u0430\u0437\u0430 \u0432 \u0430\u0434\u043c\u0438\u043d\u043a\u0435 \u0438 \u0432 \u0430\u0442\u0440\u0438\u0431\u0443\u0442\u0430\u0445 alt \u0438 title', max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('title_en', models.CharField(help_text='\u0414\u043b\u044f \u043f\u043e\u043a\u0430\u0437\u0430 \u0432 \u0430\u0434\u043c\u0438\u043d\u043a\u0435 \u0438 \u0432 \u0430\u0442\u0440\u0438\u0431\u0443\u0442\u0430\u0445 alt \u0438 title', max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=apps.banners.models.get_upload_to, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('image_ru', easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to=apps.banners.models.get_upload_to, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('image_en', easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to=apps.banners.models.get_upload_to, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('url_ru', models.URLField(blank=True, max_length=255, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('url_en', models.URLField(blank=True, max_length=255, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('button_text', models.CharField(blank=True, help_text='\u043e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u043d\u0435 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c \u043a\u043d\u043e\u043f\u043a\u0443', max_length=127, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u043a\u043d\u043e\u043f\u043a\u0435')),
                ('button_text_ru', models.CharField(blank=True, help_text='\u043e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u043d\u0435 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c \u043a\u043d\u043e\u043f\u043a\u0443', max_length=127, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u043a\u043d\u043e\u043f\u043a\u0435')),
                ('button_text_en', models.CharField(blank=True, help_text='\u043e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u043d\u0435 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c \u043a\u043d\u043e\u043f\u043a\u0443', max_length=127, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u043a\u043d\u043e\u043f\u043a\u0435')),
                ('location', models.CharField(choices=[('right', '\u0421\u043f\u0440\u0430\u0432\u0430 (\u0432\u0435\u0440\u0442\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0439)'), ('bottom', '\u0421\u043d\u0438\u0437\u0443 (\u0433\u043e\u0440\u0438\u0437\u043e\u043d\u0442\u0430\u043b\u044c\u043d\u044b\u0439)')], default='left', max_length=10, verbose_name='\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435')),
                ('show', models.BooleanField(default=True, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
                ('target_blank', models.BooleanField(default=True, verbose_name='\u041e\u0442\u043a\u0440\u044b\u0432\u0430\u0442\u044c \u0432 \u043d\u043e\u0432\u043e\u043c \u043e\u043a\u043d\u0435')),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u041d\u0430\u0447\u0430\u043b\u043e \u0440\u0430\u0437\u043c\u0435\u0449\u0435\u043d\u0438\u044f')),
                ('end_datetime', models.DateTimeField(verbose_name='\u041a\u043e\u043d\u0435\u0446 \u0440\u0430\u0437\u043c\u0435\u0449\u0435\u043d\u0438\u044f')),
                ('shows', models.IntegerField(default=0, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b')),
                ('clicks', models.IntegerField(default=0, verbose_name='\u041a\u043b\u0438\u043a\u0438')),
            ],
            options={
                'ordering': ['-show', 'location', '-end_datetime', '-start_datetime'],
                'verbose_name': '\u0431\u0430\u043d\u043d\u0435\u0440',
                'verbose_name_plural': '\u0431\u0430\u043d\u043d\u0435\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='BannerTextLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=255, verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430')),
                ('line_ru', models.CharField(max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430')),
                ('line_en', models.CharField(max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430')),
                ('big', models.BooleanField(default=False, verbose_name='\u041a\u0440\u0443\u043f\u043d\u044b\u0439 \u0448\u0440\u0438\u0444\u0442?')),
                ('order', models.IntegerField(default=10, verbose_name='\u041f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='banners.Banner', verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440')),
            ],
            options={
                'ordering': ['order', 'id'],
                'verbose_name': '\u0441\u0442\u0440\u043e\u043a\u0430',
                'verbose_name_plural': '\u0441\u0442\u0440\u043e\u043a\u0438 \u0442\u0435\u043a\u0441\u0442\u0430',
            },
        ),
    ]
