# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-27 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='\u0434\u043b\u044f \u043f\u043e\u043a\u0430\u0437\u0430 \u0432 \u0430\u0434\u043c\u0438\u043d\u043a\u0435', max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u0430\u043d\u043d\u0435\u0440\u0430')),
                ('banner_type', models.CharField(choices=[('unit', '\u0435\u0434\u0438\u043d\u0438\u0447\u043d\u044b\u0439'), ('composite', '\u0441\u043e\u0441\u0442\u0430\u0432\u043d\u043e\u0439 (\u043f\u043e\u043b\u044f \u0434\u043e\u0431\u0430\u0432\u044f\u0442\u0441\u044f \u043f\u043e\u0437\u0436\u0435)')], default='unit', max_length=15, verbose_name='\u0422\u0438\u043f \u0431\u0430\u043d\u043d\u0435\u0440\u0430')),
                ('description_h1', models.CharField(blank=True, max_length=255, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (h1)')),
                ('description_h1_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (h1)')),
                ('description_h1_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (h1)')),
                ('description_picture', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='promo_banner/pictures/', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430)')),
                ('description_picture_alt', models.CharField(blank=True, max_length=127, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (alt \u0443 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438)')),
                ('description_picture_alt_ru', models.CharField(blank=True, max_length=127, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (alt \u0443 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438)')),
                ('description_picture_alt_en', models.CharField(blank=True, max_length=127, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (alt \u0443 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438)')),
                ('description_p', models.TextField(blank=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)')),
                ('description_p_ru', models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)')),
                ('description_p_en', models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)')),
                ('link', models.URLField(verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('link_ru', models.URLField(null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('link_en', models.URLField(null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('link_text', models.CharField(help_text='\u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440, "\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433"', max_length=127, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0441\u0441\u044b\u043b\u043a\u0435')),
                ('link_text_ru', models.CharField(help_text='\u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440, "\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433"', max_length=127, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0441\u0441\u044b\u043b\u043a\u0435')),
                ('link_text_en', models.CharField(help_text='\u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440, "\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433"', max_length=127, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0441\u0441\u044b\u043b\u043a\u0435')),
                ('cover', easy_thumbnails.fields.ThumbnailerImageField(upload_to='promo_banner/covers/', verbose_name='\u041e\u0431\u043b\u043e\u0436\u043a\u0430')),
                ('video', models.URLField(blank=True, help_text='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 youtube.com', null=True, verbose_name='\u0412\u0438\u0434\u0435\u043e')),
                ('video_id', models.CharField(blank=True, editable=False, max_length=31, null=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d?')),
                ('add_dt', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u044f')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u043f\u0440\u043e\u043c\u043e-\u0431\u0430\u043d\u043d\u0435\u0440',
                'verbose_name_plural': '\u043f\u0440\u043e\u043c\u043e-\u0431\u0430\u043d\u043d\u0435\u0440 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439',
            },
        ),
        migrations.CreateModel(
            name='PromoBannerGirl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='\u043d\u0435\u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435; \u0434\u043b\u044f \u043f\u043e\u043a\u0430\u0437\u0430 \u0432 \u0430\u0434\u043c\u0438\u043d\u043a\u0435', max_length=255, verbose_name='\u0418\u043c\u044f')),
                ('photo', models.ImageField(help_text='\u0444\u0430\u0439\u043b .png', upload_to='promo_banner/girls/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='\u0412\u043a\u043b\u044e\u0447\u0435\u043d\u043e?')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='girls', to='banners.PromoBanner', verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u0444\u043e\u0442\u043e \u043c\u043e\u0434\u0435\u043b\u0438',
                'verbose_name_plural': '\u0444\u043e\u0442\u043e \u043c\u043e\u0434\u0435\u043b\u0435\u0439',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='location',
            field=models.CharField(choices=[('left', '\u0421\u043b\u0435\u0432\u0430 (\u0432\u0435\u0440\u0442\u0438\u043a\u0430\u043b\u044c\u043d\u044b\u0439)'), ('bottom', '\u0421\u043d\u0438\u0437\u0443 (\u0433\u043e\u0440\u0438\u0437\u043e\u043d\u0442\u0430\u043b\u044c\u043d\u044b\u0439)')], default='left', max_length=10, verbose_name='\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
