# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-27 15:30
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20171027_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promobannergirl',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(help_text='\u0444\u0430\u0439\u043b .png', upload_to='promo_banner/girls/', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
    ]
