# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 03:05
from __future__ import unicode_literals

import apps.banners.models
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_auto_20171027_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_text_de',
            field=models.CharField(blank=True, help_text='\u043e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u043d\u0435 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c \u043a\u043d\u043e\u043f\u043a\u0443', max_length=127, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u043a\u043d\u043e\u043f\u043a\u0435'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text_es',
            field=models.CharField(blank=True, help_text='\u043e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u043d\u0435 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c \u043a\u043d\u043e\u043f\u043a\u0443', max_length=127, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u043a\u043d\u043e\u043f\u043a\u0435'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text_fr',
            field=models.CharField(blank=True, help_text='\u043e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u043d\u0435 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c \u043a\u043d\u043e\u043f\u043a\u0443', max_length=127, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u043a\u043d\u043e\u043f\u043a\u0435'),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text_it',
            field=models.CharField(blank=True, help_text='\u043e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u043f\u0443\u0441\u0442\u044b\u043c, \u0447\u0442\u043e\u0431\u044b \u043d\u0435 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u044c \u043a\u043d\u043e\u043f\u043a\u0443', max_length=127, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u043a\u043d\u043e\u043f\u043a\u0435'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_de',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to=apps.banners.models.get_upload_to, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_es',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to=apps.banners.models.get_upload_to, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_fr',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to=apps.banners.models.get_upload_to, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_it',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to=apps.banners.models.get_upload_to, verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_de',
            field=models.CharField(help_text='\u0414\u043b\u044f \u043f\u043e\u043a\u0430\u0437\u0430 \u0432 \u0430\u0434\u043c\u0438\u043d\u043a\u0435 \u0438 \u0432 \u0430\u0442\u0440\u0438\u0431\u0443\u0442\u0430\u0445 alt \u0438 title', max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_es',
            field=models.CharField(help_text='\u0414\u043b\u044f \u043f\u043e\u043a\u0430\u0437\u0430 \u0432 \u0430\u0434\u043c\u0438\u043d\u043a\u0435 \u0438 \u0432 \u0430\u0442\u0440\u0438\u0431\u0443\u0442\u0430\u0445 alt \u0438 title', max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_fr',
            field=models.CharField(help_text='\u0414\u043b\u044f \u043f\u043e\u043a\u0430\u0437\u0430 \u0432 \u0430\u0434\u043c\u0438\u043d\u043a\u0435 \u0438 \u0432 \u0430\u0442\u0440\u0438\u0431\u0443\u0442\u0430\u0445 alt \u0438 title', max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_it',
            field=models.CharField(help_text='\u0414\u043b\u044f \u043f\u043e\u043a\u0430\u0437\u0430 \u0432 \u0430\u0434\u043c\u0438\u043d\u043a\u0435 \u0438 \u0432 \u0430\u0442\u0440\u0438\u0431\u0443\u0442\u0430\u0445 alt \u0438 title', max_length=255, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
        migrations.AddField(
            model_name='banner',
            name='url_de',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='banner',
            name='url_es',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='banner',
            name='url_fr',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='banner',
            name='url_it',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='bannertextline',
            name='line_de',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='bannertextline',
            name='line_es',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='bannertextline',
            name='line_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='bannertextline',
            name='line_it',
            field=models.CharField(max_length=255, null=True, verbose_name='\u0421\u0442\u0440\u043e\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='description_h1_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (h1)'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='description_h1_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (h1)'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='description_h1_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (h1)'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='description_h1_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (h1)'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='description_p_de',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='description_p_es',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='description_p_fr',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='description_p_it',
            field=models.TextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (\u0442\u0435\u043a\u0441\u0442)'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='description_picture_alt_de',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (alt \u0443 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438)'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='description_picture_alt_es',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (alt \u0443 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438)'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='description_picture_alt_fr',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (alt \u0443 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438)'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='description_picture_alt_it',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 (alt \u0443 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438)'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='link_de',
            field=models.URLField(null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='link_es',
            field=models.URLField(null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='link_fr',
            field=models.URLField(null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='link_it',
            field=models.URLField(null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='link_text_de',
            field=models.CharField(help_text='\u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440, "\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433"', max_length=127, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0441\u0441\u044b\u043b\u043a\u0435'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='link_text_es',
            field=models.CharField(help_text='\u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440, "\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433"', max_length=127, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0441\u0441\u044b\u043b\u043a\u0435'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='link_text_fr',
            field=models.CharField(help_text='\u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440, "\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433"', max_length=127, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0441\u0441\u044b\u043b\u043a\u0435'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='link_text_it',
            field=models.CharField(help_text='\u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440, "\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u0432 \u043a\u0430\u0442\u0430\u043b\u043e\u0433"', max_length=127, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0441\u0441\u044b\u043b\u043a\u0435'),
        ),
    ]
