# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 15:06
from __future__ import unicode_literals

from django.db import migrations


def load_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', '20171230_countries.json')


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_new_languages'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=migrations.RunPython.noop),
    ]
